<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    public function getBeschikbareActiviteiten($userid)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT a FROM App:Activity a WHERE :userid NOT MEMBER OF a.users ORDER BY a.date');

        $query->setParameter('userid', $userid);

        return $query->getResult();
    }

    public function getIngeschrevenActiviteiten($userid)
    {

        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT a FROM App:Activity a WHERE :userid MEMBER OF a.users ORDER BY a.date');

        $query->setParameter('userid', $userid);

        return $query->getResult();
    }

    public function getTotaal($activiteiten)
    {
        $totaal = 0;
        foreach ($activiteiten as $a) {
            $totaal += $a->getSoort()->getPrijs();
        }
        return $totaal;
    }

    public function findAll()
    {
        return $this->findBy([], ['date' => 'ASC']);
    }
}
